# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration                      +
# project    icecore-hashids                                    +
# repository https://github.com/arcticicestudio/icecore-hashids +
# author     Arctic Ice Studio                                  +
# email      development@arcticicestudio.com                    +
# copyright  Copyright (C) 2017                                 +
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI Documentation
#   (https://docs.travis-ci.com)
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
 directories:
    - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
script: mvn -B clean verify -P code-coverage
