# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration                      +
# project    icecore-hashids                                    +
# repository https://github.com/arcticicestudio/icecore-hashids +
# author     Arctic Ice Studio                                  +
# email      development@arcticicestudio.com                    +
# copyright  Copyright (C) 2017                                 +
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI
#   https://docs.travis-ci.com
language: java
dist: trusty
sudo: false
jdk:
  - openjdk8
  - oraclejdk8
cache:
 directories:
    - $HOME/.m2
notifications:
  email:
    on_success: never
    on_failure: change
before_script: mvn --version
script:
  - mvn -B clean verify -P node,code-coverage
  - npm install
  - npm run docs:build
after_success:
  - bash <(curl -s https://codecov.io/bash)
